#!/bin/bash

# Run PHPUnit tests
if ! vendor/bin/sail phpunit; then
    echo "PHPUnit tests failed. Push aborted."
    exit 1
fi

# If we get here, tests passed
echo "PHPUnit tests passed. Proceeding with the push."

# FIXME:Add E2E test(Playwright)

exit 0
